export const errorDictionary = {
    'CART_NOT_FOUND':'No se encontró el carrito especificado.',
    'CART_SEARCH_MISSING_ARGUMENTS':'No se pudo buscar el carrito porque el id no fue especificado.',
    'CART_CREATE_MISSING_ARGUMENTS':'No se pudo crear el carrito porque el id no fue especificado.',
    'CART_CREATE_ERROR':'Error interno del servidor al crear el carrito.',
    'CART_DATA_ERROR':'Error interno del servidor al obtener los datos del carrito.',
    'PRODUCT_NOT_FOUND':'No se encontró el producto especificado.',
    'CART_PRODUCT_DELETE_ERROR':'Error interno del servidor al eliminar producto del carrito.',
    'CART_PRODUCT_DELETE_MISSING_ARGUMENTS':'No se pudo eliminar el producto del carrito porque no se especificó el id del carrito o del producto.',
    'CART_PRODUCT_DELETE_CART_NOT_FOUND':'No se pudo buscar el producto en el carrito porque no se especificó el id del carrito o del producto.',
    'PRODUCT_ALREADY_IN_CART':'El producto a añadir ya se encuentra en el carrito.',
    'CART_PRODUCT_ADD_ERROR':'Error interno del servidor al añadir el producto al carrito.',
    'CART_PRODUCT_ADD_MISSING_ARGUMENTS':'No se pudo añadir el producto al carrito porque el id del producto o el carrito no fueron especificados.',
    'PRODUCT_QUANTITY_INCREASE_INVALID_QUANTITY':'La cantidad a añadir debe ser un número positivo al aumentar la cantidad del producto.',
    'PRODUCT_CREATE_INVALID_QUANTITY':'El precio y stock deben ser números positivos al crear el producto.',
    'PRODUCT_UPDATE_INVALID_QUANTITY':'La cantidad a añadir debe ser un número positivo al actualizar el producto.',
    'CART_PRODUCT_SEARCH_ERROR':'El producto no se encontró en el carrito.',
    'CART_PRODUCT_QUANTITYADD_MISSING_ARGUMENTS':'No se pudo aumentar la cantidad del producto ya que no se proporcionaron alguno o todos los argumentos.',
    'CART_PRODUCT_QUANTITYADD_INVALID_QUANTITY':'No se pudo aumentar la cantidad del producto ya que debe ser un numero entero.',
    'CART_PRODUCT_QUANTITYADD_ERROR':'Error al aumentar la cantidad del producto en el carrito.',
    'CART_CLEAR_ERROR':'Error interno del servidor al vaciar el carrito.',
    'CART_CLEAR_MISSING_ARGUMENTS':'No se pudo vaciar el carrito ya que no se proporcionó un id.',
    'CART_CLEAR_CART_NOT_FOUND':'No se pudo vaciar el carrito ya que no se encontró.',
    'PRODUCT_UPDATE_ERROR':'Error interno del servidor al actualizar el stock del producto.',
    'PRODUCT_UPDATE_MISSING_ARGUMENTS':'No se pudo actualizar el producto ya que no se proporcionó un id.',
    'PRODUCT_SEARCH_MISSING_ARGUMENTS':'No se pudo buscar el producto ya que no se proporcionó un id.',
    'PRODUCT_SEARCH_ERROR':'Error interno del servidor al buscar el producto',
    'PRODUCT_CREATE_MISSING_ARGUMENTS':'No se pudo crear el producto ya que no se proporcionaron uno o más datos.',
    'PRODUCT_CREATE_ERROR':'Error interno del servidor al crear el producto.',
    'PRODUCT_DELETE_MISSING_ARGUMENTS':'No se pudo eliminar el producto ya que no se proporcionó un id.',
    'PRODUCT_DELETE_NOT_FOUND':'No se encontró el producto a eliminar.',
    'PRODUCT_DELETE_ERROR':'Error interno del servidor al eliminar el producto.'
};